# Generated by Django 5.1.10 on 2025-07-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100, verbose_name="公司名")),
                (
                    "application_deadline",
                    models.DateField(blank=True, null=True, verbose_name="投递截至日期"),
                ),
                (
                    "online_test_deadline",
                    models.DateField(blank=True, null=True, verbose_name="网测截至日期"),
                ),
                (
                    "first_interview_date",
                    models.DateField(blank=True, null=True, verbose_name="一面日期"),
                ),
                (
                    "second_interview_date",
                    models.DateField(blank=True, null=True, verbose_name="二面日期"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, max_length=100, verbose_name="备注"),
                ),
                (
                    "application_rejected",
                    models.BooleanField(default=False, verbose_name="投递淘汰"),
                ),
                (
                    "online_test_rejected",
                    models.BooleanField(default=False, verbose_name="网测淘汰"),
                ),
                (
                    "first_interview_rejected",
                    models.BooleanField(default=False, verbose_name="一面淘汰"),
                ),
                (
                    "second_interview_rejected",
                    models.BooleanField(default=False, verbose_name="二面淘汰"),
                ),
                (
                    "notes_rejected",
                    models.BooleanField(default=False, verbose_name="备注淘汰"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "求职申请",
                "verbose_name_plural": "求职申请",
                "ordering": ["-created_at"],
            },
        ),
    ]
