# Generated by Django 5.1.10 on 2025-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="application_rejected",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="first_interview_rejected",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="notes_rejected",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="online_test_rejected",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="second_interview_rejected",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="application_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="投递状态",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="first_interview_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="一面状态",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="notes_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="备注状态",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="online_test_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="网测状态",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="second_interview_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="二面状态",
            ),
        ),
    ]
