# Generated by Django 5.1.10 on 2025-10-27 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_rename_notes_status_to_notes_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="上传 PDF 文件（可选）",
                null=True,
                upload_to="job_pdfs/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="PDF 文件",
            ),
        ),
    ]
