# Generated by Django 5.2.7 on 2025-11-03 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_jobapplication_pdf_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="application_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Application Deadline"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="application_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="Application Status",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="company_name",
            field=models.CharField(max_length=100, verbose_name="Company Name"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="first_interview_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="First Interview Date"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="first_interview_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="First Interview Status",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="notes",
            field=models.TextField(blank=True, max_length=100, verbose_name="Memo"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="notes_result",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="Memo Result",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="online_test_deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="Online Test Deadline"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="online_test_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="Online Test Status",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Only PDF",
                null=True,
                upload_to="job_pdfs/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="ES & Interview Notes",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="second_interview_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Second Interview Date"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="second_interview_status",
            field=models.CharField(
                choices=[("---", "---"), ("pass", "Pass"), ("fail", "Fail")],
                default="---",
                max_length=10,
                verbose_name="Second Interview Status",
            ),
        ),
    ]
