# Generated by Django 5.2.7 on 2026-01-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_alter_jobapplication_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="notes",
            field=models.TextField(blank=True, max_length=500, verbose_name="Memo"),
        ),
    ]
