# Generated by Django 5.2.7 on 2026-01-21 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_jobattachment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobAttachment",
        ),
    ]
